version: "3.3"

services:
  rabbit:
    container_name: rabbit
    image: container.k8s.nexiles.cloud/nexiles/rabbitmq:3.8.16-management
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    volumes:
      - rabbit-data:/var/lib/rabbitmq:delegated
      - ./docker/rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:delegated
      - ./docker/rabbit/rabbit_definitions.json:/opt/definitions.json:delegated
    ports:
      - "1883:1883" # MQTT
      - "5672:5672" # AMQP
      - "15672:15672" # WEB
    networks:
      app:
        aliases:
          - "mqtt.broker.local"

  openhab:
    container_name: openhab
    image: "openhab/openhab:3.1.0"
    command: "./start_debug.sh"
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
      - ./docker/openhab/openhab_conf/services/runtime.cfg:/openhab/conf/services/runtime.cfg
      - ./docker/openhab/openhab_userdata/etc/log4j2.xml:/openhab/userdata/etc/log4j2.xml
      - ./openhab_addons:/openhab/addons
      - ./openhab_conf:/openhab/conf
      - ./openhab_userdata:/openhab/userdata
    ports:
      - "9091:8080" # WEB
      - "8101:8101" # SSH
      - "5005:5005" # WEB
    networks:
      - app
    environment:
      USER_ID: "1000" # nexiles
      GROUP_ID: "1000" # nexiles
      OPENHAB_HTTP_PORT: "8080" # WEB
      OPENHAB_HTTPS_PORT: "8443" # WEBS
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"

volumes:
  rabbit-data:
    driver: local

networks:
  app:
